security:
  oauth2:
    client:
      registration:
        google:
          clientId : ${Google_Client_Id}
          clientSecret: ${Google_Client_Secret}
          scope:
            - email
            - profile
