spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-id : ${Google_Client_Id}
            client-secret: ${Google_Client_Secret}
            scope:
              - email
              - profile