server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://${Db_URL}:${Db_PORT}/${Db_Name}?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${Db_User_Name}
    password: ${Db_User_PassWord}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO_MODE}
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
        default_batch_fetch_size: 500
    #        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    #    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    database: mysql
    generate-ddl: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: ${SQL_INIT_MODE}

  mvc:
    path match:
      matching-strategy: ant_path_matcher
  config.import: classpath:application-credentials.yml
  profiles:
    active: credentials
    include:
      - aws
      - credentials
      - jwt
      - oauth

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

gpt:
  key: ${GPT_KEY}
